# Generated by Django 5.1.1 on 2024-09-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=20)),
                ('stock_ticker', models.CharField(blank=True, max_length=8)),
                ('date', models.DateTimeField(blank=True)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20)),
                ('volume', models.IntegerField(blank=True, max_length=20)),
                ('dividends', models.FloatField(blank=True, max_length=6)),
                ('stock_splits', models.FloatField(blank=True, max_length=6)),
            ],
        ),
    ]
