# Generated by Django 5.1.1 on 2024-09-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0003_alter_stockinfo_close_alter_stockinfo_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=20)),
                ('stock_ticker', models.CharField(blank=True, default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StockDataframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.FloatField(blank=True, max_length=6, null=True)),
                ('stock_splits', models.FloatField(blank=True, max_length=6, null=True)),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analyzer.companyticker')),
            ],
        ),
        migrations.DeleteModel(
            name='StockInfo',
        ),
    ]
