# Generated by Django 5.1.1 on 2024-10-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0004_companyticker_stockdataframe_delete_stockinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdataframe',
            name='stock_ticker',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
