# Generated by Django 5.1.1 on 2024-10-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0005_alter_stockdataframe_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdataframe',
            name='stock_ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analyzer.companyticker'),
        ),
    ]
