# Generated by Django 5.1.1 on 2024-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0006_alter_stockdataframe_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyticker',
            name='five_year_graph',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
