# Generated by Django 5.1.1 on 2024-10-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0007_companyticker_five_year_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyticker',
            name='five_year_graph',
        ),
    ]
