# Generated by Django 5.1.1 on 2024-10-05 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0009_companyticker_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyticker',
            name='users',
            field=models.ManyToManyField(related_name='tickers', to=settings.AUTH_USER_MODEL),
        ),
    ]
